imagebase/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
admin.autodiscover()


from core.views import DashboardView, DashboardDataView
from upload.views import UploadView
from image.views import ImageView, ImageTagView, ImageUpdateView, ImageDeleteView
from prefs.views import SettingsView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'imagebase.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', DashboardView.as_view(), name='dashboard'),
    url(r'^dashboard/data/$', DashboardDataView.as_view(), name='dashboard_data'),
    url(r'^dashboard/(.*?)$', DashboardView.as_view(), name='dashboard'),
    url(r'^upload/$', UploadView.as_view(), name='upload'),
    url(r'^image/(?P<pk>\d+)/content/$', ImageView.as_view(template_name='image_content.html'), name='image_content'),
    url(r'^image/(?P<pk>\d+)/panel/$', ImageView.as_view(template_name='image_panel_content.html'), name='image_panel_content'),
    url(r'^image/(?P<pk>\d+)/$', ImageView.as_view(), name='image'),
    url(r'^image/(?P<pk>\d+)/update/$', ImageUpdateView.as_view(), name='image_update'),
    url(r'^image/(?P<pk>\d+)/update/content/$', ImageUpdateView.as_view(template_name='image_update_content.html'), name='image_update_content'),
    url(r'^image/(?P<pk>\d+)/delete/$', ImageDeleteView.as_view(), name='image_delete'),
    url(r'^image/(?P<pk>\d+)/delete/content/$', ImageDeleteView.as_view(template_name='image_delete_content.html'), name='image_delete_content'),
    url(r'^tags/$', ImageTagView.as_view(), name='image_tag'),
    url(r'^tags/(?P<slug>[\w\-]+)/$', ImageTagView.as_view(), name='image_tag_list'),
    url(r'^settings/(?P<pk>\d+)/$', SettingsView.as_view(), name='setting'),

    url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imagebase/core/models.py
from django.db import models

# Create your models here.

imagebase/ft/models.py
from django.db import models

# Create your models here.

imagebase/image/models.py
from django.db import models
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager

class Image(models.Model):
    title = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='imagebase')
    tags = TaggableManager(blank=True)

    def __unicode__(self):
        return '%s' % self.title

    def get_absolute_url(self):
        return reverse('image', args=[self.id])

imagebase/prefs/models.py
from django.db import models
from django.core.urlresolvers import reverse

class ImagebaseSettings(models.Model):
    show_id = models.BooleanField(default=False)
    show_title = models.BooleanField(default=True)
    show_tags = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('setting', args=[self.id])

imagebase/upload/models.py
from django.db import models

# Create your models here.

imagebase/image/forms.py
from django import forms

class ImageDeleteForm(forms.Form):
    pass

imagebase/prefs/forms.py
from django.forms import ModelForm

from .models import ImagebaseSettings

class SettingsForm(ModelForm):

    class Meta:
        model = ImagebaseSettings

imagebase/core/views.py
import json
from django.views.generic import ListView
from django.shortcuts import HttpResponse
from django.core.urlresolvers import reverse

from image.models import Image
from prefs.models import ImagebaseSettings

class DashboardView(ListView):

    template_name = 'dashboard.html'
    model = Image

    def get_imagebase_settings(self):
        # get_or_create returns a tuple so we only want the first item (the object)
        imagebase_setting = ImagebaseSettings.objects.get_or_create()
        return imagebase_setting[0]

    def get_queryset(self):
        return self.model.objects.all().order_by('-created')

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['imagebase_settings'] = self.get_imagebase_settings()
        return context

class DashboardDataView(DashboardView):

    def get(self, *args, **kwargs):

        data = {
            'images': {}
        }

        for image in self.get_queryset():
            data['images'][image.id] = {
                'viewUrl': image.get_absolute_url(),
                'contentUrl': reverse('image_content', args=(image.id,)),
                'updateUrl': reverse('image_update_content', args=(image.id,)),
                'deleteUrl': reverse('image_delete_content', args=(image.id,)),
                'panelUrl': reverse('image_panel_content', args=(image.id,))
            }

        return HttpResponse(json.dumps(data))

imagebase/ft/views.py
from django.shortcuts import render

# Create your views here.

imagebase/image/views.py
from django.contrib import messages
from django.views.generic import UpdateView, ListView, DetailView, DeleteView
from django.core.urlresolvers import reverse_lazy

from taggit.models import Tag


from prefs.models import ImagebaseSettings
from .models import Image
from .forms import ImageDeleteForm

class ImageView(DetailView):
    template_name = 'image.html'
    model = Image

    def get_imagebase_settings(self):
        # get_or_create returns a tuple so we only want the first item (the object)
        # duplicated in the DashboardView - in a real application this wouldn't be done
        imagebase_setting = ImagebaseSettings.objects.get_or_create()
        return imagebase_setting[0]


    def get_context_data(self, **kwargs):
        context = super(ImageView, self).get_context_data(**kwargs)
        related_images = Image.objects.filter(tags__name__in=list(self.object.tags.all())).distinct().exclude(id__exact=self.object.id)
        context['related_images'] = related_images
        context['imagebase_settings'] = self.get_imagebase_settings()
        return context

class ImageUpdateView(UpdateView):
    template_name = 'image_update.html'
    model = Image
    fields = ['image', 'title', 'tags']

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, 'Image updated successfully')
        return super(ImageUpdateView, self).form_valid(form)


class ImageDeleteView(DeleteView):
    template_name = 'image_delete.html'
    model = Image
    success_url = reverse_lazy('dashboard')

    def get_context_data(self, **kwargs):
        context = super(ImageDeleteView, self).get_context_data(**kwargs)
        context['form'] = ImageDeleteForm
        return context

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, 'Image deleted successfully')
        return super(ImageUpdateView, self).form_valid(form)

class ImageTagView(ListView):
    template_name = 'tags.html'
    model = Tag

    def get_context_data(self, **kwargs):
        context = super(ImageTagView, self).get_context_data(**kwargs)
        tag = self.kwargs.get('slug')
        images = Image.objects.filter(tags__name__in=[tag])
        context['images'] = images
        context['tag_slug'] = tag
        return context

imagebase/prefs/views.py
from django.contrib import messages
from django.views.generic import UpdateView

from .models import ImagebaseSettings

class SettingsView(UpdateView):
    template_name = 'settings.html'
    model = ImagebaseSettings

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, 'Settings updated successfully')
        return super(SettingsView, self).form_valid(form)

    def get_object(self, queryset=None):
        return ImagebaseSettings.objects.get_or_create()[0]

imagebase/upload/views.py
from django.contrib import messages
from django.views.generic import CreateView

from image.models import Image

class UploadView(CreateView):
    template_name = 'upload.html'
    model = Image
    fields = ['image']

    def form_valid(self, form):
        messages.add_message(self.request, messages.SUCCESS, 'Image uploaded successfully')
        return super(UploadView, self).form_valid(form)

imagebase/core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Imagebase: {% block pagetitle %}{% endblock %}</title>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'imagebase/css/app.css' %}"/>
</head>
<body>

<div class="container">
    <div class="contain-to-grid">
        <nav class="top-bar" data-topbar>
            <ul class="title-area">
                <li class="name">
                    <h1><a href="/">Imagebase</a></h1>
                </li>
                <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
            </ul>

            <section class="top-bar-section">
                <ul class="right">
                    <li><a href="/dashboard/">Dashboard</a></li>
                    <li><a href="/upload/">Upload</a></li>
                    <li><a href="/tags/">Tags</a></li>
                    <li><a href="/settings/1/">Settings</a></li>
                </ul>
            </section>
        </nav>
    </div>
    <div class="row">
        <div class="small-12 columns">
            {% if messages %}

                    {% for message in messages %}
                        <div {% if message.tags %} data-alert class="alert-box" class="{{ message.tags }}"{% endif %}>{{ message }}</div>
                    {% endfor %}

            {% endif %}

            <main>
                {% block main %}{% endblock %}
                <div id="modal" class="reveal-modal" data-reveal></div>
            </main>
        </div>
    </div>
</div>

<script src="{% static 'imagebase/bower_components/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'imagebase/bower_components/foundation/js/foundation.min.js' %}"></script>
<script src="{% static 'imagebase/bower_components/underscore/underscore.js' %}"></script>
<script src="{% static 'imagebase/bower_components/backbone/backbone.js' %}"></script>
<script src="{% static 'imagebase/js/plugins.js' %}"></script>
<script src="{% static 'imagebase/js/app.js' %}"></script>
</body>
</html>

imagebase/core/templates/dashboard.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block pagetitle %}Dashboard{% endblock %}

{% block main %}
    <h2>Dashboard</h2>

    <div class="row">
        <div class="medium-12 columns" id="image-master-container">
            <ul class="small-block-grid-2 medium-block-grid-3 image-grid">
                {% for image in image_list %}
                    <li class="image-panel" data-pk="{{ image.id }}">
                        {% include 'image_panel_content.html' %}
                    </li>
                {% empty %}
                    <li><a href="{% url 'upload' %}">Upload an image</a></li>
                {% endfor %}
            </ul>
        </div>
        {% spaceless %}
        <div data-sticky class="medium-4 columns card">
            <div class="side pjax-container panel front" id="image-detail-container"></div>
            <div class="side pjax-container panel back" id="image-update-container"></div>
        </div>
        {% endspaceless %}

    </div>


{% endblock %}

imagebase/image/templates/image.html
{% extends 'base.html' %}

{% block main %}

    {% include 'image_content.html' %}

{% endblock %}

imagebase/image/templates/image_content.html
{% load thumbnail %}

<h2 class="heading">{{ image.title }}</h2>
<p>
    {% thumbnail image.image "300" crop="center" as im %}
        <div class="main_image_large_container">
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="" class="main_image_large"/>
        </div>
    {% endthumbnail %}
</p>
<a href="{% url 'image_update' image.id %}" class="label success" data-pjax>edit image</a>
<a href="{% url 'image_delete' image.id %}" class="label alert" data-pjax>delete image</a>

<!--<a href="{% url 'dashboard' %}" class="" data-pjax>close</a> -->

<h4>Tags</h4>
<p>
    {% for tag in image.tags.all %}
        <a href="{% url 'image_tag_list' slug=tag %}">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>

<hr/>

<h4>Related: <strong>by tag</strong></h4>
{% if related_images %}
    <ul class="small-block-grid-4">
        {% for image in related_images %}
            <li>
                {% thumbnail image.image '100x100' crop='center' as im %}
                    <a href="{% url 'image' pk=image.id %}" class="thumbnail"><img src="{{ im.url }}" alt=""/></a>
                {% endthumbnail %}
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>There are currently no related images.</p>
{% endif %}

imagebase/image/templates/image_delete.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block main %}

    {% include 'image_delete_content.html' %}
{% endblock %}

imagebase/image/templates/image_delete_content.html
{% load thumbnail %}

<h2 class="heading">Delete Image{% if image.title %}: <strong>{{ image.title }}</strong>{% endif %}</h2>

{% thumbnail image.image "150" crop="center" as im %}
    <div class="main_image_container">
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="" class="main_image"/>
    </div>
{% endthumbnail %}

<div class="row">
    <div class="medium-6 columns">
        <form action="{% url 'image_delete' pk=image.id %}" role='form' method="post" class="delete_form">
            {% csrf_token %}
            {{ form }}
            <hr/>
            <button type="submit" class="radius button">Confirm Delete</button>
            <a href="{% url 'image' pk=image.id %}" data-pjax>Cancel</a>
        </form>
    </div>
</div>

imagebase/image/templates/image_panel_content.html
{% load thumbnail %}

    <a href="{% url 'image' pk=image.id %}" data-pjax class="thumbnail">
        {% thumbnail image.image '320x240' crop='center' as im %}

            <img src="{{ im.url }}" alt=""/>

        {% endthumbnail %}

        <div class="panel">
            <ul id="image_{{ image.id }}_attributes" class="no-bullet image-attributes">
                {% if imagebase_settings.show_id %}
                    <li class="attr_id"><small>id</small> {{ image.id }}</li>
                {% endif %}
                {% if imagebase_settings.show_title %}
                    <li class="attr_title"><small>title</small> {{ image.title }}</li>
                {% endif %}
                {% if imagebase_settings.show_tags %}
                    <li class="attr_tags"><small>tags</small> {{ image.tags.names|join:' ' }}</li>
                {% endif %}
            </ul>
        </div>
    </a>

imagebase/image/templates/image_update.html
{% extends 'base.html' %}

{% block main %}

    {% include 'image_update_content.html' %}

{% endblock %}

imagebase/image/templates/image_update_content.html
{% load thumbnail %}

<h2 class="heading">Edit Image{% if image.title %}: <strong>{{ image.title }}</strong>{% endif %}</h2>

{% thumbnail image.image "150" crop="center" as im %}
    <div class="main_image_container">
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="" class="main_image"/>
    </div>
{% endthumbnail %}

<div class="row">
    <div class="medium-8 columns">
        <form action="{% url 'image_update' image.id %}" role='form' method="post" class="update_form" enctype="multipart/form-data">
            {% csrf_token %}

            {{ form }}

            <hr/>
            <button type="submit" class="radius button">Update</button> <a href="{% url 'image' pk=image.id %}" data-pjax>Cancel</a>
        </form>
    </div>
</div>

imagebase/image/templates/tags.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block main %}

    <h2>{% if tag_slug %}Images tagged with: <strong>{{ tag_slug }}</strong>{% else %}Tags{% endif %}</h2>

            {% if object_list %}
            <ul class="inline-list">
                {% for tag_object in object_list %}
                    <li class="{% if tag_object.slug == tag_slug %}active{% else %}{% endif %}"><a href="{% url 'image_tag_list' slug=tag_object.slug %}" class="class="label label-{% if tag_object.slug == tag_slug %}primary{% else %}info{% endif %}"">{{ tag_object.name }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
                <p>There are no tags yet</p>
            {% endif %}

            <ul class="small-block-grid-4">
            {% for image in images %}
                <li>
                    {% thumbnail image.image '320x240' crop='center' as im %}
                        <a href="{% url 'image' pk=image.id  %}" class="thumbnail"><img src="{{ im.url }}" alt=""/></a></li>
                    {% endthumbnail %}
                </li>
            {% endfor %}
            </ul>

{% endblock %}

imagebase/prefs/templates/settings.html
{% extends 'base.html' %}

{% block pagetitle %}Settings{% endblock %}

{% block main %}
    <h2>Settings</h2>
    <form action="" method="post" id="settings_form">
        {% csrf_token %}
        {% for field in form %}
            <div class="">
                {{ field }}{{ field.label_tag }}
            </div>
        {% endfor %}

        <hr/>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

imagebase/upload/templates/upload.html
{% extends 'base.html' %}

{% block pagetitle %}Upload{% endblock %}


{% block main %}
    <h2>Upload image</h2>
    <form action="" role="form" method="post" class="upload_form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Upload" class="btn btn-primary"/> <a href="{% url 'dashboard' %}">Cancel</a>
    </form>
{% endblock %}